// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VentaPieMVC.Models;

namespace VentaPieMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200220183135_seedData")]
    partial class seedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VentaPieMVC.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "CAT1"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "CAT2"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "CAT3"
                        });
                });

            modelBuilder.Entity("VentaPieMVC.Models.Pie", b =>
                {
                    b.Property<int>("PieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AllegryInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPieOfTheWeek")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PieId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Pies");

                    b.HasData(
                        new
                        {
                            PieId = 1,
                            AllegryInformation = "",
                            CategoryId = 1,
                            ImageThumbnailUrl = "",
                            ImageUrl = "",
                            InStock = true,
                            IsPieOfTheWeek = true,
                            LongDescription = "lonooonong",
                            Name = "Apple Pie",
                            Price = 0m,
                            ShortDescription = "short deds"
                        },
                        new
                        {
                            PieId = 2,
                            AllegryInformation = "",
                            CategoryId = 2,
                            ImageThumbnailUrl = "",
                            ImageUrl = "",
                            InStock = true,
                            IsPieOfTheWeek = false,
                            LongDescription = "lonooonong",
                            Name = "Cheese Pie",
                            Price = 0m,
                            ShortDescription = "short deds"
                        },
                        new
                        {
                            PieId = 3,
                            AllegryInformation = "",
                            CategoryId = 3,
                            ImageThumbnailUrl = "",
                            ImageUrl = "",
                            InStock = true,
                            IsPieOfTheWeek = false,
                            LongDescription = "lonooonong",
                            Name = "stuff pie",
                            Price = 0m,
                            ShortDescription = "short deds"
                        });
                });

            modelBuilder.Entity("VentaPieMVC.Models.Pie", b =>
                {
                    b.HasOne("VentaPieMVC.Models.Category", "Category")
                        .WithMany("Pies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
